ci: attempt updating :help index multiple times

diff --git a/.github/workflows/update-help-index.yml b/.github/workflows/update-help-index.yml
--- a/.github/workflows/update-help-index.yml
+++ b/.github/workflows/update-help-index.yml
@@ -1,9 +1,9 @@
 name: Update :help Search Index
 
 on:
-  # twice per month (2:15 at the 2nd and 15th of the month)
+  # twice per month (4:35 at the 2nd and 15th of the month)
   schedule:
-    - cron: "15 2 2,15 * *"
+    - cron: "35 4 2,15 * *"
 
   # allow triggering manually
   workflow_dispatch: {}
@@ -17,12 +17,16 @@ jobs:
   build:
     runs-on: macos-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
+      - uses: actions/checkout@v4
       - name: Update :help Search Index
         run: |
-          zsh ./.github/help-index/create-index.sh
+          for i in {1..3}; do
+            echo "Attempt #$i"
+            zsh ./.github/help-index/create-index.sh && exit 0
+            sleep 5
+          done
+          echo "Multiple attempts to update the index failed. Aborting."
+          exit 1
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: "chore: Updated :help index"
