ci: more robust `:help` indexing workflow

diff --git a/.github/workflows/update-help-index.yml b/.github/workflows/update-help-index.yml
--- a/.github/workflows/update-help-index.yml
+++ b/.github/workflows/update-help-index.yml
@@ -5,8 +5,14 @@ on:
   schedule:
     - cron: "35 4 2,15 * *"
 
-  # allow triggering manually
+  # triggering manually
   workflow_dispatch: {}
+
+  # when this file or the script for re-indexing is changed
+  push:
+    paths:
+      - .github/workflows/update-help-index.yml
+      - .github/help-index/create-index.sh
 
 permissions:
   contents: write
@@ -19,14 +25,11 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Update :help Search Index
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
         run: |
-          for i in {1..5}; do
-            echo "Attempt #$i"
-            zsh ./.github/help-index/create-index.sh && exit 0
-            sleep 30
-          done
-          echo "Multiple attempts to update the index failed. Aborting."
-          exit 1
+          zsh ./.github/help-index/create-index.sh
+          exit $? # inherit exit code
       - uses: stefanzweifel/git-auto-commit-action@v5
         with:
-          commit_message: "chore: Updated :help index"
+          commit_message: "chore: Updated `:help` index"
